name: open-data-capture
volumes:
  caddy_data:
  mssql_data:
services:
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      - SITE_ADDRESS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  api:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-api:${RELEASE_CHANNEL}
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - RELEASE_VERSION
    depends_on:
      - mssql
    restart: unless-stopped
    environment:
      - GATEWAY_INTERNAL_NETWORK_URL=http://gateway:80
      - MSSQL_PORT=1433
      - MSSQL_USER=testuser
      - MSSQL_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - NODE_ENV=production
      - DANGEROUSLY_DISABLE_PBKDF2_ITERATION
      - DEBUG
      - GATEWAY_API_KEY
      - GATEWAY_ENABLED
      - GATEWAY_REFRESH_INTERVAL
      - GATEWAY_SITE_ADDRESS
      - SECRET_KEY
      - THROTTLER_ENABLED
      - VERBOSE
    expose:
      - 80
  gateway:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-gateway:${RELEASE_CHANNEL}
    build:
      args:
        - RELEASE_VERSION
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - ${GATEWAY_PORT}:80
    expose:
      - 80
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - GATEWAY_API_KEY
  web:
    image: ghcr.io/douglasneuroinformatics/open-data-capture-web:${RELEASE_CHANNEL}
    build:
      args:
        - RELEASE_VERSION
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - API_BASE_URL=/api
      - CONTACT_EMAIL
      - DOCS_URL
      - GITHUB_REPO_URL
      - LICENSE_URL
      - GATEWAY_ENABLED
      - PLAUSIBLE_BASE_URL
      - PLAUSIBLE_WEB_DATA_DOMAIN
    expose:
      - 80
    restart: unless-stopped
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - '1433:1433'
    expose:
      - 1433
    restart: unless-stopped
    volumes:
      - ./data/mssql:/var/opt/mssql
